import type { Account, SubscriptionKey } from '@/stores/useAccounts'
import type {
  DashboardDataSource,
  DashboardMetricId,
  DashboardMetricUnit,
  DashboardWidgetType,
} from './types'

export interface DashboardSourceMeta {
  id: DashboardDataSource
  label: string
  description: string
  icon: string
  /** An array passes when the account holds ANY of the keys. */
  requires?: SubscriptionKey | SubscriptionKey[]
}

export interface DashboardMetricDescriptor {
  id: DashboardMetricId
  dataSource: DashboardDataSource
  label: string
  description: string
  defaultTitle: string
  defaultWidgetType: DashboardWidgetType
  supportedWidgetTypes: DashboardWidgetType[]
  unit: DashboardMetricUnit
  icon?: string
  drilldown: {
    routeName: string
    label: string
  }
  aiKeywords: string[]
}

export const DASHBOARD_SOURCE_META: Record<DashboardDataSource, DashboardSourceMeta> = {
  commerce: {
    id: 'commerce',
    label: 'Commerce',
    description: 'Orders, revenue, conversion, and storefront performance.',
    icon: 'shopping-cart',
    requires: ['commerce', 'retail'],
  },
  marketing: {
    id: 'marketing',
    label: 'Marketing',
    description: 'Campaign performance, deliverability, and engagement.',
    icon: 'megaphone',
    requires: 'marketing',
  },
  analytics: {
    id: 'analytics',
    label: 'Analytics',
    description: 'Cross-channel overview metrics and business trends.',
    icon: 'line-chart',
    requires: 'analytics',
  },
  contacts: {
    id: 'contacts',
    label: 'Contacts',
    description: 'Audience growth, segmentation, and contact quality.',
    icon: 'users',
  },
  service: {
    id: 'service',
    label: 'Service',
    description: 'Ticket backlog, response load, and support health.',
    icon: 'headset',
    requires: 'service',
  },
  neto: {
    id: 'neto',
    label: 'Neto',
    description: 'Neto storefront orders, products, and inventory.',
    icon: 'store',
  },
  retail: {
    id: 'retail',
    label: 'Retail',
    description: 'Point-of-sale insights: registers, locations, and in-store sales.',
    icon: 'shopping-bag',
    requires: 'retail',
  },
  merchandising: {
    id: 'merchandising',
    label: 'Merchandise',
    description: 'AI-powered discovery, search, and recommendation analytics.',
    icon: 'wand-sparkles',
    requires: 'commerce',
  },
}

const metricCatalog: Record<DashboardDataSource, DashboardMetricDescriptor[]> = {
  commerce: [
    {
      id: 'commerce_revenue',
      dataSource: 'commerce',
      label: 'Revenue',
      description: 'Gross revenue from placed orders.',
      defaultTitle: 'Revenue',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'dollar-sign',
      drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
      aiKeywords: ['revenue', 'sales', 'gmv'],
    },
    {
      id: 'commerce_orders',
      dataSource: 'commerce',
      label: 'Orders',
      description: 'Count of orders placed in the selected period.',
      defaultTitle: 'Orders',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'shopping-cart',
      drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
      aiKeywords: ['orders', 'order count', 'purchases'],
    },
    {
      id: 'commerce_aov',
      dataSource: 'commerce',
      label: 'Average Order Value',
      description: 'Average order value in the selected period.',
      defaultTitle: 'Average Order Value',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'tag',
      drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
      aiKeywords: ['aov', 'average order value'],
    },
    {
      id: 'commerce_conversion_rate',
      dataSource: 'commerce',
      label: 'Conversion Rate',
      description: 'Share of sessions that converted to an order.',
      defaultTitle: 'Conversion Rate',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'percent',
      icon: 'percent',
      drilldown: { routeName: 'OrdersReport', label: 'Open orders report' },
      aiKeywords: ['conversion rate', 'conversion', 'session conversion'],
    },
    {
      id: 'commerce_revenue_over_time',
      dataSource: 'commerce',
      label: 'Revenue Over Time',
      description: 'Revenue trend for the selected period.',
      defaultTitle: 'Revenue Over Time',
      defaultWidgetType: 'timeseries',
      supportedWidgetTypes: ['timeseries'],
      unit: 'currency',
      drilldown: { routeName: 'OrdersReport', label: 'Open orders report' },
      aiKeywords: ['revenue trend', 'revenue over time', 'sales trend'],
    },
    {
      id: 'commerce_revenue_by_channel',
      dataSource: 'commerce',
      label: 'Revenue by Channel',
      description: 'Compare revenue across mock sales channels.',
      defaultTitle: 'Revenue by Channel',
      defaultWidgetType: 'bar',
      supportedWidgetTypes: ['bar'],
      unit: 'currency',
      drilldown: { routeName: 'SalesSummary', label: 'Open sales summary' },
      aiKeywords: ['revenue by channel', 'sales channel', 'channel mix'],
    },
    {
      id: 'commerce_recent_orders',
      dataSource: 'commerce',
      label: 'Recent Orders',
      description: 'Latest order activity.',
      defaultTitle: 'Recent Orders',
      defaultWidgetType: 'table',
      supportedWidgetTypes: ['table'],
      unit: 'count',
      drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
      aiKeywords: ['recent orders', 'order table', 'latest orders'],
    },
    {
      id: 'overview_metric_explorer',
      dataSource: 'commerce',
      label: 'Metric Explorer',
      description: 'Revenue, orders, AOV, and conversion in one selectable strip with a trend chart.',
      defaultTitle: 'Store performance',
      defaultWidgetType: 'metric_explorer',
      supportedWidgetTypes: ['metric_explorer'],
      unit: 'currency',
      icon: 'chart-spline',
      drilldown: { routeName: 'OrdersReport', label: 'Open orders report' },
      aiKeywords: ['metric explorer', 'kpi strip', 'store performance', 'revenue orders aov conversion'],
    },
    {
      id: 'commerce_revenue_attribution',
      dataSource: 'commerce',
      label: 'Revenue Attribution',
      description: 'Share of revenue attributed to each acquisition channel.',
      defaultTitle: 'Where revenue comes from',
      defaultWidgetType: 'donut',
      supportedWidgetTypes: ['donut'],
      unit: 'currency',
      icon: 'chart-pie',
      drilldown: { routeName: 'OrdersReport', label: 'Open orders report' },
      aiKeywords: ['revenue attribution', 'where revenue comes from', 'channel attribution'],
    },
    {
      id: 'commerce_orders_by_channel',
      dataSource: 'commerce',
      label: 'Orders by Sales Channel',
      description: 'Order counts split across sales channels.',
      defaultTitle: 'Orders by sales channel',
      defaultWidgetType: 'donut',
      supportedWidgetTypes: ['donut'],
      unit: 'count',
      icon: 'chart-pie',
      drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
      aiKeywords: ['orders by channel', 'sales channel split', 'channel orders'],
    },
    {
      id: 'commerce_new_vs_returning',
      dataSource: 'commerce',
      label: 'New vs Returning',
      description: 'Share of orders from returning customers vs first-time buyers.',
      defaultTitle: 'New vs returning',
      defaultWidgetType: 'donut',
      supportedWidgetTypes: ['donut'],
      unit: 'percent',
      icon: 'users',
      drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
      aiKeywords: ['new vs returning', 'repeat customers', 'customer loyalty split'],
    },
    {
      id: 'commerce_revenue_goal',
      dataSource: 'commerce',
      label: 'Revenue Goal',
      description: 'Progress toward the rolling revenue goal for the period.',
      defaultTitle: 'Rolling revenue goal',
      defaultWidgetType: 'gauge',
      supportedWidgetTypes: ['gauge'],
      unit: 'percent',
      icon: 'goal',
      drilldown: { routeName: 'OrdersReport', label: 'Open orders report' },
      aiKeywords: ['revenue goal', 'goal gauge', 'target progress'],
    },
    {
      id: 'overview_tabs',
      dataSource: 'commerce',
      label: 'Orders & Activity',
      description: 'Recent orders, live activity, and top campaigns in one tabbed card.',
      defaultTitle: 'Orders & activity',
      defaultWidgetType: 'tabs',
      supportedWidgetTypes: ['tabs'],
      unit: 'count',
      icon: 'layout-list',
      drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
      aiKeywords: ['recent orders tabs', 'orders and activity', 'tabbed overview'],
    },
    {
      id: 'commerce_channel_weekly',
      dataSource: 'commerce',
      label: 'Online vs In-store',
      description: 'Weekly revenue stacked by online and in-store channels.',
      defaultTitle: 'Online vs in-store',
      defaultWidgetType: 'stacked_bar',
      supportedWidgetTypes: ['stacked_bar'],
      unit: 'currency',
      icon: 'bar-chart-3',
      drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
      aiKeywords: ['online vs in-store', 'stacked bar', 'weekly revenue by channel', 'pos vs web'],
    },
    {
      id: 'commerce_best_sellers',
      dataSource: 'commerce',
      label: 'Best Sellers',
      description: 'Top products by revenue with unit counts.',
      defaultTitle: 'Best sellers',
      defaultWidgetType: 'bar_list',
      supportedWidgetTypes: ['bar_list'],
      unit: 'currency',
      icon: 'trophy',
      drilldown: { routeName: 'ProductsList', label: 'Open products' },
      aiKeywords: ['best sellers', 'top products', 'top skus'],
    },
    {
      id: 'commerce_fulfillment_queue',
      dataSource: 'commerce',
      label: 'Fulfillment Queue',
      description: 'Orders in the fulfillment pipeline by stage.',
      defaultTitle: 'Fulfillment queue',
      defaultWidgetType: 'breakdown',
      supportedWidgetTypes: ['breakdown'],
      unit: 'count',
      icon: 'truck',
      drilldown: { routeName: 'Fulfillments', label: 'Open fulfillment' },
      aiKeywords: ['fulfillment queue', 'shipping pipeline', 'orders to ship'],
    },
  ],
  marketing: [
    {
      id: 'marketing_open_rate',
      dataSource: 'marketing',
      label: 'Open Rate',
      description: 'Average campaign open rate.',
      defaultTitle: 'Open Rate',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'percent',
      icon: 'mail-open',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['open rate', 'email opens'],
    },
    {
      id: 'marketing_click_rate',
      dataSource: 'marketing',
      label: 'Click Rate',
      description: 'Average click-through rate for sent campaigns.',
      defaultTitle: 'Click Rate',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'percent',
      icon: 'mouse-pointer-click',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['click rate', 'ctr', 'click-through rate'],
    },
    {
      id: 'marketing_sends',
      dataSource: 'marketing',
      label: 'Campaign Sends',
      description: 'Total sends for completed campaigns.',
      defaultTitle: 'Campaign Sends',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'send',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['sends', 'campaign sends', 'email volume'],
    },
    {
      id: 'marketing_open_rate_over_time',
      dataSource: 'marketing',
      label: 'Open Rate Trend',
      description: 'Open rate across recent campaigns.',
      defaultTitle: 'Open Rate Trend',
      defaultWidgetType: 'timeseries',
      supportedWidgetTypes: ['timeseries'],
      unit: 'percent',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['open rate trend', 'opens over time', 'show open rate trend'],
    },
    {
      id: 'marketing_campaign_revenue',
      dataSource: 'marketing',
      label: 'Campaign Revenue by Folder',
      description: 'Attributed revenue across campaign folders.',
      defaultTitle: 'Campaign Revenue',
      defaultWidgetType: 'bar',
      supportedWidgetTypes: ['bar'],
      unit: 'currency',
      drilldown: { routeName: 'EmailCampaigns', label: 'Open email campaigns' },
      aiKeywords: ['campaign revenue', 'revenue by campaign', 'campaign performance'],
    },
    {
      id: 'marketing_top_campaigns',
      dataSource: 'marketing',
      label: 'Top Campaigns',
      description: 'Top performing campaigns by revenue.',
      defaultTitle: 'Top Campaigns',
      defaultWidgetType: 'table',
      supportedWidgetTypes: ['table'],
      unit: 'count',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['top campaigns', 'best campaigns', 'campaign table'],
    },
    {
      id: 'marketing_email_volume',
      dataSource: 'marketing',
      label: 'Email Volume',
      description: 'Sent and delivered email volume over time.',
      defaultTitle: 'Email Volume',
      defaultWidgetType: 'timeseries',
      supportedWidgetTypes: ['timeseries'],
      unit: 'count',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['email volume', 'sent delivered', 'email trend'],
    },
    {
      id: 'marketing_recent_campaigns',
      dataSource: 'marketing',
      label: 'Recent Sent Campaigns',
      description: 'Latest campaigns with delivery stats.',
      defaultTitle: 'Recent Sent Campaigns',
      defaultWidgetType: 'table',
      supportedWidgetTypes: ['table'],
      unit: 'count',
      drilldown: { routeName: 'EmailCampaigns', label: 'Open email campaigns' },
      aiKeywords: ['recent campaigns', 'sent campaigns', 'campaign list'],
    },
    {
      id: 'marketing_total_campaign_revenue',
      dataSource: 'marketing',
      label: 'Total Campaign Revenue',
      description: 'Revenue attributed to email campaigns over time.',
      defaultTitle: 'Total Campaign Revenue',
      defaultWidgetType: 'timeseries',
      supportedWidgetTypes: ['timeseries', 'bar'],
      unit: 'currency',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['campaign revenue', 'total campaign revenue', 'email revenue'],
    },
    {
      id: 'marketing_deliverability_score',
      dataSource: 'marketing',
      label: 'Deliverability Score',
      description: 'Overall email deliverability health score.',
      defaultTitle: 'Deliverability Score',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'shield-check',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['deliverability', 'deliverability score', 'inbox placement'],
    },
    {
      id: 'demo_channel_trend',
      dataSource: 'marketing',
      label: 'Revenue by Channel (trend)',
      description: 'Weekly revenue across acquisition channels — a multi-series comparison.',
      defaultTitle: 'Revenue by channel',
      defaultWidgetType: 'timeseries',
      supportedWidgetTypes: ['timeseries', 'bar'],
      unit: 'currency',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['revenue by channel', 'channel trend', 'channel comparison'],
    },
    {
      id: 'demo_channel_mix',
      dataSource: 'marketing',
      label: 'Traffic Mix',
      description: 'Share of sessions across acquisition channels.',
      defaultTitle: 'Traffic mix',
      defaultWidgetType: 'pie',
      supportedWidgetTypes: ['pie'],
      unit: 'percent',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['traffic mix', 'channel mix', 'session share', 'sources'],
    },
    {
      id: 'marketing_live_activity',
      dataSource: 'marketing',
      label: 'Live Activity',
      description: 'Real-time activity feed of recent events.',
      defaultTitle: 'Live activity',
      defaultWidgetType: 'activity',
      supportedWidgetTypes: ['activity'],
      unit: 'count',
      icon: 'activity',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['activity', 'live activity', 'recent events', 'feed'],
    },
    {
      id: 'overview_campaign_funnel',
      dataSource: 'marketing',
      label: 'Campaign Funnel',
      description: 'Marketing sends through to commerce orders, stage by stage.',
      defaultTitle: 'Campaign to purchase funnel',
      defaultWidgetType: 'funnel',
      supportedWidgetTypes: ['funnel'],
      unit: 'count',
      icon: 'filter',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['funnel', 'campaign funnel', 'purchase funnel', 'conversion funnel'],
    },
    {
      id: 'marketing_deliverability_breakdown',
      dataSource: 'marketing',
      label: 'Email Deliverability',
      description: 'Delivered share with bounce, complaint, and unsubscribe rates.',
      defaultTitle: 'Email deliverability',
      defaultWidgetType: 'breakdown',
      supportedWidgetTypes: ['breakdown'],
      unit: 'percent',
      icon: 'mail-check',
      drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
      aiKeywords: ['deliverability', 'bounce rate', 'spam complaints', 'inbox placement'],
    },
    {
      id: 'marketing_journeys_in_flight',
      dataSource: 'marketing',
      label: 'Journeys in Flight',
      description: 'Contacts currently moving through automations.',
      defaultTitle: 'Journeys in flight',
      defaultWidgetType: 'breakdown',
      supportedWidgetTypes: ['breakdown'],
      unit: 'count',
      icon: 'workflow',
      drilldown: { routeName: 'Journeys', label: 'Open journeys' },
      aiKeywords: ['journeys', 'automations in flight', 'active journeys'],
    },
  ],
  analytics: [
    {
      id: 'design_palette',
      dataSource: 'analytics',
      label: 'Dashboard Palette',
      description: 'Every shade used by the Overview chart family, for design review.',
      defaultTitle: 'Dashboard palette',
      defaultWidgetType: 'palette',
      supportedWidgetTypes: ['palette'],
      unit: 'count',
      icon: 'palette',
      drilldown: { routeName: 'DashboardShadcn', label: 'Open design lab' },
      aiKeywords: ['palette', 'colors', 'shades', 'design review', 'chart colors'],
    },
    {
      id: 'overview_attention',
      dataSource: 'analytics',
      label: 'Needs Your Attention',
      description: 'Prioritized cross-cloud items that need action.',
      defaultTitle: 'Needs your attention',
      defaultWidgetType: 'attention',
      supportedWidgetTypes: ['attention'],
      unit: 'count',
      icon: 'bell-ring',
      drilldown: { routeName: 'dashboard-detail', label: 'Overview' },
      aiKeywords: ['attention', 'alerts', 'action items', 'issues'],
    },
    {
      id: 'davinci_insights',
      dataSource: 'analytics',
      label: 'Da Vinci Insights',
      description: 'AI-generated observations with suggested next steps.',
      defaultTitle: 'Da Vinci insights',
      defaultWidgetType: 'insights',
      supportedWidgetTypes: ['insights'],
      unit: 'count',
      icon: 'sparkles',
      drilldown: { routeName: 'dashboard-detail', label: 'Overview' },
      aiKeywords: ['insights', 'da vinci', 'ai insights', 'recommendations'],
    },
    {
      id: 'analytics_total_revenue',
      dataSource: 'analytics',
      label: 'Total Revenue',
      description: 'Total attributed revenue across the business.',
      defaultTitle: 'Total Revenue',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'trending-up',
      drilldown: { routeName: 'MonthlyTotals', label: 'Open monthly totals' },
      aiKeywords: ['total revenue', 'overall revenue'],
    },
    {
      id: 'analytics_total_orders',
      dataSource: 'analytics',
      label: 'Total Orders',
      description: 'Order volume across the selected period.',
      defaultTitle: 'Total Orders',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'package',
      drilldown: { routeName: 'OrdersReport', label: 'Open orders report' },
      aiKeywords: ['total orders', 'order volume'],
    },
    {
      id: 'analytics_active_subscribers',
      dataSource: 'analytics',
      label: 'Active Subscribers',
      description: 'Subscriber count from analytics summary.',
      defaultTitle: 'Active Subscribers',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'users',
      drilldown: { routeName: 'MonthlyTotals', label: 'Open monthly totals' },
      aiKeywords: ['subscribers', 'active subscribers', 'audience size'],
    },
    {
      id: 'analytics_sends_over_time',
      dataSource: 'analytics',
      label: 'Sends Over Time',
      description: 'Sends trend for the analytics period.',
      defaultTitle: 'Sends Over Time',
      defaultWidgetType: 'timeseries',
      supportedWidgetTypes: ['timeseries'],
      unit: 'count',
      drilldown: { routeName: 'MonthlyTotals', label: 'Open monthly totals' },
      aiKeywords: ['sends over time', 'send trend', 'email volume trend'],
    },
  ],
  contacts: [
    {
      id: 'contacts_total',
      dataSource: 'contacts',
      label: 'Total Contacts',
      description: 'All audience records in the workspace.',
      defaultTitle: 'Total Contacts',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'contact-round',
      drilldown: { routeName: 'AllContacts', label: 'Open all contacts' },
      aiKeywords: ['contacts', 'total contacts', 'audience'],
    },
    {
      id: 'contacts_subscribed',
      dataSource: 'contacts',
      label: 'Subscribed Contacts',
      description: 'Contacts currently subscribed to messaging.',
      defaultTitle: 'Subscribed Contacts',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'user-check',
      drilldown: { routeName: 'AllContacts', label: 'Open all contacts' },
      aiKeywords: ['subscribed contacts', 'subscribers'],
    },
    {
      id: 'contacts_growth',
      dataSource: 'contacts',
      label: 'Contact Growth',
      description: 'Contact creation trend over time.',
      defaultTitle: 'Contact Growth',
      defaultWidgetType: 'timeseries',
      supportedWidgetTypes: ['timeseries'],
      unit: 'count',
      drilldown: { routeName: 'AllContacts', label: 'Open all contacts' },
      aiKeywords: ['contact growth', 'audience growth'],
    },
    {
      id: 'contacts_top_segments',
      dataSource: 'contacts',
      label: 'Top Segments',
      description: 'Largest segments by count.',
      defaultTitle: 'Top Segments',
      defaultWidgetType: 'table',
      supportedWidgetTypes: ['table'],
      unit: 'count',
      drilldown: { routeName: 'Segments', label: 'Open segments' },
      aiKeywords: ['segments', 'top segments', 'audience segments'],
    },
    {
      id: 'contacts_by_domain',
      dataSource: 'contacts',
      label: 'Email Address by Domain',
      description: 'Contact distribution across email domains.',
      defaultTitle: 'Email Address by Domain',
      defaultWidgetType: 'bar',
      supportedWidgetTypes: ['bar'],
      unit: 'count',
      drilldown: { routeName: 'AllContacts', label: 'Open all contacts' },
      aiKeywords: ['email domain', 'domain breakdown', 'contacts by domain'],
    },
    {
      id: 'contacts_subscriber_summary',
      dataSource: 'contacts',
      label: 'Subscriber Summary',
      description: 'Subscriber and unsubscriber counts with net growth.',
      defaultTitle: 'Subscriber Summary',
      defaultWidgetType: 'table',
      supportedWidgetTypes: ['table'],
      unit: 'count',
      drilldown: { routeName: 'AllContacts', label: 'Open all contacts' },
      aiKeywords: ['subscriber summary', 'subscribers', 'unsubscribers', 'net growth'],
    },
  ],
  service: [
    {
      id: 'service_open_tickets',
      dataSource: 'service',
      label: 'Open Tickets',
      description: 'Current unresolved support tickets.',
      defaultTitle: 'Open Tickets',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'inbox',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['open tickets', 'support backlog'],
    },
    {
      id: 'service_resolution_rate',
      dataSource: 'service',
      label: 'Resolution Rate',
      description: 'Resolved tickets as a share of total tickets.',
      defaultTitle: 'Resolution Rate',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'percent',
      icon: 'check-circle',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['resolution rate', 'ticket resolution'],
    },
    {
      id: 'service_ticket_volume',
      dataSource: 'service',
      label: 'Ticket Volume',
      description: 'Support tickets created over time.',
      defaultTitle: 'Ticket Volume',
      defaultWidgetType: 'timeseries',
      supportedWidgetTypes: ['timeseries'],
      unit: 'count',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['ticket volume', 'support tickets over time'],
    },
    {
      id: 'service_recent_tickets',
      dataSource: 'service',
      label: 'Recent Tickets',
      description: 'Latest ticket activity with status and assignee.',
      defaultTitle: 'Recent Tickets',
      defaultWidgetType: 'table',
      supportedWidgetTypes: ['table'],
      unit: 'count',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['recent tickets', 'ticket table', 'support queue'],
    },
    {
      id: 'service_new_tickets',
      dataSource: 'service',
      label: 'New Tickets',
      description: 'Tickets created in the selected period.',
      defaultTitle: 'New Tickets',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'ticket',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['new tickets', 'incoming tickets'],
    },
    {
      id: 'service_pending_tickets',
      dataSource: 'service',
      label: 'Pending & On-Hold',
      description: 'Tickets waiting for a response or on hold.',
      defaultTitle: 'Pending & On-Hold',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'clock',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['pending tickets', 'on hold tickets'],
    },
    {
      id: 'service_unresolved_tickets',
      dataSource: 'service',
      label: 'Unresolved Tickets',
      description: 'All tickets not yet marked as resolved.',
      defaultTitle: 'Unresolved Tickets',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'alert-circle',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['unresolved tickets', 'backlog'],
    },
    {
      id: 'service_support_health',
      dataSource: 'service',
      label: 'Support Health',
      description: 'Open tickets with unresolved backlog and oldest ticket age.',
      defaultTitle: 'Support health',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'heart-pulse',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['support health', 'open tickets', 'ticket backlog'],
    },
    {
      id: 'service_tickets_by_channel',
      dataSource: 'service',
      label: 'Tickets by Channel',
      description: 'Ticket distribution across support channels.',
      defaultTitle: 'Tickets by Channel',
      defaultWidgetType: 'bar',
      supportedWidgetTypes: ['bar'],
      unit: 'count',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['tickets by channel', 'channel breakdown'],
    },
    {
      id: 'service_tickets_by_type',
      dataSource: 'service',
      label: 'Tickets by Type',
      description: 'Ticket count grouped by issue type.',
      defaultTitle: 'Tickets by Type',
      defaultWidgetType: 'bar',
      supportedWidgetTypes: ['bar'],
      unit: 'count',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['tickets by type', 'ticket types', 'issue type'],
    },
    {
      id: 'service_tickets_breakdown',
      dataSource: 'service',
      label: 'Service Tickets',
      description: 'Open ticket count with reply, SLA, and resolution breakdown.',
      defaultTitle: 'Service tickets',
      defaultWidgetType: 'breakdown',
      supportedWidgetTypes: ['breakdown'],
      unit: 'count',
      icon: 'life-buoy',
      drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
      aiKeywords: ['service tickets', 'ticket breakdown', 'sla', 'support queue'],
    },
  ],
  neto: [],
  retail: [
    {
      id: 'retail_revenue',
      dataSource: 'retail',
      label: 'Revenue',
      description: 'Gross POS revenue for the selected period.',
      defaultTitle: 'Revenue',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'dollar-sign',
      drilldown: { routeName: 'SalesOrders', label: 'Retail revenue' },
      aiKeywords: ['retail', 'revenue', 'sales', 'pos'],
    },
    {
      id: 'retail_sale_count',
      dataSource: 'retail',
      label: 'Sale Count',
      description: 'Number of completed sales transactions.',
      defaultTitle: 'Sale Count',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'receipt',
      drilldown: { routeName: 'SalesOrders', label: 'Retail sales' },
      aiKeywords: ['retail', 'sale count', 'transactions'],
    },
    {
      id: 'retail_customer_count',
      dataSource: 'retail',
      label: 'Customer Count',
      description: 'Unique customers who made a purchase.',
      defaultTitle: 'Customer Count',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'users',
      drilldown: { routeName: 'AllContacts', label: 'Retail customers' },
      aiKeywords: ['retail', 'customers', 'shoppers'],
    },
    {
      id: 'retail_gross_profit',
      dataSource: 'retail',
      label: 'Gross Profit',
      description: 'Revenue minus cost of goods sold.',
      defaultTitle: 'Gross Profit',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'trending-up',
      drilldown: { routeName: 'SalesOrders', label: 'Retail profit' },
      aiKeywords: ['retail', 'gross profit', 'margin'],
    },
    {
      id: 'retail_discounted',
      dataSource: 'retail',
      label: 'Discounted',
      description: 'Total discount value applied across sales.',
      defaultTitle: 'Discounted',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'tag',
      drilldown: { routeName: 'Coupons', label: 'Coupons & discounts' },
      aiKeywords: ['retail', 'discount', 'promotion'],
    },
    {
      id: 'retail_discounted_pct',
      dataSource: 'retail',
      label: 'Discounted (%)',
      description: 'Share of revenue lost to discounts.',
      defaultTitle: 'Discounted (%)',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'percent',
      icon: 'percent',
      drilldown: { routeName: 'Coupons', label: 'Coupons & discounts' },
      aiKeywords: ['retail', 'discount percent', 'markdown rate'],
    },
    {
      id: 'retail_avg_sale_value',
      dataSource: 'retail',
      label: 'Avg Sale Value',
      description: 'Average value per completed sale.',
      defaultTitle: 'Avg Sale Value',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'shopping-cart',
      drilldown: { routeName: 'SalesOrders', label: 'Retail basket size' },
      aiKeywords: ['retail', 'average sale', 'basket value'],
    },
    {
      id: 'retail_avg_items_per_sale',
      dataSource: 'retail',
      label: 'Avg Items / Sale',
      description: 'Average items per completed sale.',
      defaultTitle: 'Avg Items / Sale',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'package',
      drilldown: { routeName: 'ProductsList', label: 'Retail product mix' },
      aiKeywords: ['retail', 'items per sale', 'units per transaction'],
    },
    {
      id: 'retail_sales_today',
      dataSource: 'retail',
      label: 'Sales Today',
      description: 'Total sales revenue for today across all stores.',
      defaultTitle: 'Sales Today',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'trending-up',
      drilldown: { routeName: 'SalesOrders', label: 'Retail sales today' },
      aiKeywords: ['retail', 'sales today', 'today revenue'],
    },
    {
      id: 'retail_avg_basket',
      dataSource: 'retail',
      label: 'Average Basket',
      description: 'Average basket value per transaction.',
      defaultTitle: 'Average Basket',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'shopping-bag',
      drilldown: { routeName: 'SalesOrders', label: 'Retail basket size' },
      aiKeywords: ['retail', 'basket size', 'average basket'],
    },
    {
      id: 'retail_returns_today',
      dataSource: 'retail',
      label: 'Returns Today',
      description: 'Refunds and partial refunds processed today.',
      defaultTitle: 'Returns Today',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'count',
      icon: 'undo-2',
      drilldown: { routeName: 'SalesOrders', label: 'Retail returns' },
      aiKeywords: ['retail', 'returns', 'refunds'],
    },
    {
      id: 'retail_sales_by_location',
      dataSource: 'retail',
      label: 'Sales by Location',
      description: 'Revenue contribution per retail location.',
      defaultTitle: 'Sales by Location',
      defaultWidgetType: 'bar',
      supportedWidgetTypes: ['bar'],
      unit: 'currency',
      drilldown: { routeName: 'RetailLocations', label: 'Retail locations' },
      aiKeywords: ['retail', 'sales by location', 'store performance'],
    },
    {
      id: 'retail_top_skus',
      dataSource: 'retail',
      label: 'Top SKUs',
      description: 'Best selling SKUs by revenue.',
      defaultTitle: 'Top SKUs',
      defaultWidgetType: 'table',
      supportedWidgetTypes: ['table'],
      unit: 'currency',
      drilldown: { routeName: 'ProductsList', label: 'Retail products' },
      aiKeywords: ['retail', 'top skus', 'best sellers'],
    },
    {
      id: 'retail_top_associates',
      dataSource: 'retail',
      label: 'Top staff',
      description: 'Top performing sales staff by revenue.',
      defaultTitle: 'Top staff',
      defaultWidgetType: 'table',
      supportedWidgetTypes: ['table'],
      unit: 'currency',
      drilldown: { routeName: 'RetailStaff', label: 'Retail staff' },
      aiKeywords: ['retail', 'top staff', 'best associates'],
    },
    {
      id: 'retail_today_breakdown',
      dataSource: 'retail',
      label: 'Retail Today',
      description: 'POS takings today with a per-location breakdown.',
      defaultTitle: 'Retail today',
      defaultWidgetType: 'bar_list',
      supportedWidgetTypes: ['bar_list'],
      unit: 'currency',
      icon: 'store',
      drilldown: { routeName: 'RetailLocations', label: 'Retail locations' },
      aiKeywords: ['retail today', 'pos takings', 'sales by location today'],
    },
  ],
  merchandising: [
    {
      id: 'merch_total_revenue',
      dataSource: 'merchandising',
      label: 'Total Revenue',
      description: 'Total storefront revenue across all channels.',
      defaultTitle: 'Total Revenue',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'dollar-sign',
      drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
      aiKeywords: ['merchandise', 'total revenue', 'storefront revenue'],
    },
    {
      id: 'merch_cloud_revenue',
      dataSource: 'merchandising',
      label: 'MerchCloud-driven Revenue',
      description: 'Revenue attributed to MerchCloud recommendations and search.',
      defaultTitle: 'MerchCloud-driven Revenue',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'sparkles',
      drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
      aiKeywords: ['merchandise', 'merch cloud revenue', 'discovery revenue'],
    },
    {
      id: 'merch_cloud_share',
      dataSource: 'merchandising',
      label: 'MerchCloud Share',
      description: 'Percentage of total revenue driven by MerchCloud.',
      defaultTitle: 'MerchCloud Share',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'percent',
      icon: 'pie-chart',
      drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
      aiKeywords: ['merchandise', 'merch cloud share', 'contribution percent'],
    },
    {
      id: 'merch_aov',
      dataSource: 'merchandising',
      label: 'Avg. Order Value',
      description: 'Average order value across merchandised sessions.',
      defaultTitle: 'Avg. Order Value',
      defaultWidgetType: 'kpi',
      supportedWidgetTypes: ['kpi'],
      unit: 'currency',
      icon: 'receipt',
      drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
      aiKeywords: ['merchandise', 'aov', 'order value'],
    },
    {
      id: 'merch_revenue_trend',
      dataSource: 'merchandising',
      label: 'Revenue Trend',
      description: 'Daily total revenue vs MerchCloud-driven revenue.',
      defaultTitle: 'Revenue Trend',
      defaultWidgetType: 'timeseries',
      supportedWidgetTypes: ['timeseries'],
      unit: 'currency',
      drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
      aiKeywords: ['merchandise', 'revenue trend', 'merch cloud trend'],
    },
    {
      id: 'merch_contribution',
      dataSource: 'merchandising',
      label: 'MerchCloud Contribution',
      description: 'Share of total revenue from MerchCloud vs other channels.',
      defaultTitle: 'MerchCloud Contribution',
      defaultWidgetType: 'bar',
      supportedWidgetTypes: ['bar'],
      unit: 'currency',
      drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
      aiKeywords: ['merchandise', 'contribution', 'merch cloud share breakdown'],
    },
  ],
}

export function getMetricDescriptor(metricId: DashboardMetricId): DashboardMetricDescriptor | undefined {
  return Object.values(metricCatalog)
    .flat()
    .find((metric) => metric.id === metricId)
}

export function isDashboardSourceAvailable(source: DashboardDataSource, account: Account | undefined): boolean {
  if (!account) return false
  const requirement = DASHBOARD_SOURCE_META[source].requires
  if (!requirement) return true
  return Array.isArray(requirement)
    ? requirement.some((key) => account.subscriptions.includes(key))
    : account.subscriptions.includes(requirement)
}

export function getAvailableDashboardSources(account: Account | undefined): DashboardSourceMeta[] {
  if (!account) return []
  return Object.values(DASHBOARD_SOURCE_META).filter((source) => isDashboardSourceAvailable(source.id, account))
}

export function getMetricsForSource(source: DashboardDataSource, account: Account | undefined): DashboardMetricDescriptor[] {
  if (!isDashboardSourceAvailable(source, account)) return []
  return metricCatalog[source]
}

export function getAvailableMetrics(account: Account | undefined): DashboardMetricDescriptor[] {
  if (!account) return []
  return getAvailableDashboardSources(account).flatMap((source) => metricCatalog[source.id])
}
