import type { DashboardWidgetLibraryEntry } from './types'

export const WIDGET_LIBRARY: DashboardWidgetLibraryEntry[] = [
  {
    id: 'lib-revenue',
    title: 'Revenue',
    description: 'Total sales for the selected period',
    category: 'commerce',
    type: 'kpi',
    icon: 'dollar-sign',
    recommended: true,
    metricId: 'commerce_revenue',
    dataSource: 'commerce',
    drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
  },
  {
    id: 'lib-orders',
    title: 'Orders',
    description: 'Track total orders and compare with previous period',
    category: 'commerce',
    type: 'kpi',
    icon: 'shopping-cart',
    recommended: true,
    metricId: 'commerce_orders',
    dataSource: 'commerce',
    drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
  },
  {
    id: 'lib-revenue-over-time',
    title: 'Revenue over time',
    description: 'Daily revenue trend compared with previous period',
    category: 'commerce',
    type: 'timeseries',
    icon: 'line-chart',
    recommended: true,
    metricId: 'commerce_revenue_over_time',
    dataSource: 'commerce',
    chartVariant: 'area',
    drilldown: { routeName: 'OrdersReport', label: 'Open orders report' },
  },
  {
    id: 'lib-top-products',
    title: 'Top products',
    description: 'Best performing products by revenue or units sold',
    category: 'commerce',
    type: 'table',
    icon: 'package',
    metricId: 'commerce_recent_orders',
    dataSource: 'commerce',
    drilldown: { routeName: 'SalesOrders', label: 'Open sales orders' },
  },
  {
    id: 'lib-open-rate',
    title: 'Open rate',
    description: 'Email open rate across campaigns',
    category: 'marketing',
    type: 'kpi',
    icon: 'mail-open',
    recommended: true,
    metricId: 'marketing_open_rate',
    dataSource: 'marketing',
    drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
  },
  {
    id: 'lib-campaign-activity',
    title: 'Campaign activity',
    description: 'Recent sends, updates, and campaign events',
    category: 'marketing',
    type: 'activity',
    icon: 'activity',
    metricId: 'marketing_live_activity',
    dataSource: 'marketing',
    drilldown: { routeName: 'CampaignReports', label: 'Open campaign reports' },
  },
  {
    id: 'lib-total-contacts',
    title: 'Total contacts',
    description: 'Total contacts and growth over time',
    category: 'marketing',
    type: 'kpi',
    icon: 'contact-round',
    recommended: true,
    metricId: 'contacts_total',
    dataSource: 'contacts',
    drilldown: { routeName: 'AllContacts', label: 'Open all contacts' },
  },
  {
    id: 'lib-open-tickets',
    title: 'Open tickets',
    description: 'Track open support requests and SLA risk',
    category: 'service',
    type: 'kpi',
    icon: 'inbox',
    metricId: 'service_open_tickets',
    dataSource: 'service',
    drilldown: { routeName: 'Tickets', label: 'Open ticket queue' },
  },
  {
    id: 'lib-retail-revenue',
    title: 'Retail revenue',
    description: 'Gross POS revenue for the selected period',
    category: 'retail',
    type: 'kpi',
    icon: 'dollar-sign',
    recommended: true,
    metricId: 'retail_revenue',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail revenue' },
  },
  {
    id: 'lib-retail-sale-count',
    title: 'Sale count',
    description: 'Completed POS sale transactions',
    category: 'retail',
    type: 'kpi',
    icon: 'receipt',
    metricId: 'retail_sale_count',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail sales' },
  },
  {
    id: 'lib-retail-customer-count',
    title: 'Customer count',
    description: 'Unique customers who made a purchase',
    category: 'retail',
    type: 'kpi',
    icon: 'users',
    metricId: 'retail_customer_count',
    dataSource: 'retail',
    drilldown: { routeName: 'AllContacts', label: 'Retail customers' },
  },
  {
    id: 'lib-retail-gross-profit',
    title: 'Gross profit',
    description: 'Revenue minus cost of goods sold',
    category: 'retail',
    type: 'kpi',
    icon: 'trending-up',
    recommended: true,
    metricId: 'retail_gross_profit',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail profit' },
  },
  {
    id: 'lib-retail-discounted',
    title: 'Discounted',
    description: 'Total discount value applied across sales',
    category: 'retail',
    type: 'kpi',
    icon: 'tag',
    metricId: 'retail_discounted',
    dataSource: 'retail',
    drilldown: { routeName: 'Coupons', label: 'Coupons & discounts' },
  },
  {
    id: 'lib-retail-discounted-pct',
    title: 'Discounted (%)',
    description: 'Share of revenue lost to discounts',
    category: 'retail',
    type: 'kpi',
    icon: 'percent',
    metricId: 'retail_discounted_pct',
    dataSource: 'retail',
    drilldown: { routeName: 'Coupons', label: 'Coupons & discounts' },
  },
  {
    id: 'lib-retail-avg-sale-value',
    title: 'Avg sale value',
    description: 'Average value per completed sale',
    category: 'retail',
    type: 'kpi',
    icon: 'shopping-cart',
    metricId: 'retail_avg_sale_value',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail basket size' },
  },
  {
    id: 'lib-retail-avg-items-per-sale',
    title: 'Avg items / sale',
    description: 'Average items per completed sale',
    category: 'retail',
    type: 'kpi',
    icon: 'package',
    metricId: 'retail_avg_items_per_sale',
    dataSource: 'retail',
    drilldown: { routeName: 'ProductsList', label: 'Retail product mix' },
  },
  {
    id: 'lib-retail-sales-today',
    title: 'Sales today',
    description: 'Total sales revenue for today across all stores',
    category: 'retail',
    type: 'kpi',
    icon: 'trending-up',
    metricId: 'retail_sales_today',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail sales today' },
  },
  {
    id: 'lib-retail-avg-basket',
    title: 'Average basket',
    description: 'Average basket value per transaction',
    category: 'retail',
    type: 'kpi',
    icon: 'shopping-bag',
    metricId: 'retail_avg_basket',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail basket size' },
  },
  {
    id: 'lib-retail-returns-today',
    title: 'Returns today',
    description: 'Refunds and partial refunds processed today',
    category: 'retail',
    type: 'kpi',
    icon: 'undo-2',
    metricId: 'retail_returns_today',
    dataSource: 'retail',
    drilldown: { routeName: 'SalesOrders', label: 'Retail returns' },
  },
  {
    id: 'lib-retail-sales-by-location',
    title: 'Sales by location',
    description: 'Revenue contribution per retail location',
    category: 'retail',
    type: 'bar',
    icon: 'map-pin',
    metricId: 'retail_sales_by_location',
    dataSource: 'retail',
    drilldown: { routeName: 'RetailLocations', label: 'Retail locations' },
  },
  {
    id: 'lib-retail-top-skus',
    title: 'Top SKUs',
    description: 'Best selling SKUs by revenue',
    category: 'retail',
    type: 'table',
    icon: 'package',
    metricId: 'retail_top_skus',
    dataSource: 'retail',
    drilldown: { routeName: 'ProductsList', label: 'Retail products' },
  },
  {
    id: 'lib-retail-top-associates',
    title: 'Top associates',
    description: 'Top performing sales associates by revenue',
    category: 'retail',
    type: 'table',
    icon: 'user-round',
    metricId: 'retail_top_associates',
    dataSource: 'retail',
    drilldown: { routeName: 'RetailAssociates', label: 'Retail associates' },
  },
  {
    id: 'lib-merch-total-revenue',
    title: 'Total revenue',
    description: 'Total storefront revenue across all channels',
    category: 'merchandising',
    type: 'kpi',
    icon: 'dollar-sign',
    recommended: true,
    metricId: 'merch_total_revenue',
    dataSource: 'merchandising',
    drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
  },
  {
    id: 'lib-merch-cloud-revenue',
    title: 'MerchCloud-driven revenue',
    description: 'Revenue attributed to MerchCloud recommendations and search',
    category: 'merchandising',
    type: 'kpi',
    icon: 'sparkles',
    recommended: true,
    metricId: 'merch_cloud_revenue',
    dataSource: 'merchandising',
    drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
  },
  {
    id: 'lib-merch-cloud-share',
    title: 'MerchCloud share',
    description: 'Percentage of total revenue driven by MerchCloud',
    category: 'merchandising',
    type: 'kpi',
    icon: 'pie-chart',
    metricId: 'merch_cloud_share',
    dataSource: 'merchandising',
    drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
  },
  {
    id: 'lib-merch-aov',
    title: 'Avg. order value',
    description: 'Average order value across merchandised sessions',
    category: 'merchandising',
    type: 'kpi',
    icon: 'receipt',
    metricId: 'merch_aov',
    dataSource: 'merchandising',
    drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
  },
  {
    id: 'lib-merch-revenue-trend',
    title: 'Revenue trend',
    description: 'Daily total revenue vs MerchCloud-driven revenue',
    category: 'merchandising',
    type: 'timeseries',
    icon: 'line-chart',
    recommended: true,
    metricId: 'merch_revenue_trend',
    dataSource: 'merchandising',
    chartVariant: 'area',
    drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
  },
  {
    id: 'lib-merch-contribution',
    title: 'MerchCloud contribution',
    description: 'Share of total revenue from MerchCloud vs other channels',
    category: 'merchandising',
    type: 'bar',
    icon: 'pie-chart',
    metricId: 'merch_contribution',
    dataSource: 'merchandising',
    drilldown: { routeName: 'MerchandisingHome', label: 'Merchandise overview' },
  },
]
