import {
  mp_color_light_background,
  mp_color_light_surface,
  mp_color_light_surfaceVariant,
  mp_color_light_surfaceTint,
  mp_color_light_onSurfaceVariant,
  mp_color_light_primary,
  mp_color_light_primaryDarken,
  mp_color_light_secondary,
  mp_color_light_secondaryDarken,
  mp_color_light_success,
  mp_color_light_successDarken,
  mp_color_light_warning,
  mp_color_light_warningDarken,
  mp_color_light_error,
  mp_color_light_errorDarken,
  mp_color_light_info,
  mp_color_light_onPrimary,
  mp_color_light_onSecondary,
  mp_color_light_onSuccess,
  mp_color_light_onError,
  mp_color_light_onWarning,
  mp_color_light_primaryContainer,
  mp_color_light_onPrimaryContainer,
  mp_color_light_successContainer,
  mp_color_light_onSuccessContainer,
  mp_color_light_warningContainer,
  mp_color_light_onWarningContainer,
  mp_color_light_errorContainer,
  mp_color_light_onErrorContainer,
  mp_color_light_surfaceBright,
  mp_color_light_outline,
  mp_color_light_outlineVariant,
  mp_color_light_border,
  mp_color_light_textPrimary,
  mp_color_light_flowLogic_primary,
  mp_color_light_flowLogic_onPrimary,
  mp_color_light_flowLogic_container,
  mp_color_blue_50,
  mp_color_blue_100,
  mp_color_blue_200,
  mp_color_blue_700,
  mp_color_blue_900,
  mp_color_neutral_100,
  mp_color_neutral_200,
  mp_color_dark_background,
  mp_color_dark_surface,
  mp_color_dark_surfaceVariant,
  mp_color_dark_surfaceTint,
  mp_color_dark_onSurfaceVariant,
  mp_color_dark_primary,
  mp_color_dark_primaryDarken,
  mp_color_dark_secondary,
  mp_color_dark_secondaryDarken,
  mp_color_dark_success,
  mp_color_dark_successDarken,
  mp_color_dark_warning,
  mp_color_dark_warningDarken,
  mp_color_dark_error,
  mp_color_dark_errorDarken,
  mp_color_dark_info,
  mp_color_dark_onPrimary,
  mp_color_dark_onSecondary,
  mp_color_dark_onSuccess,
  mp_color_dark_onError,
  mp_color_dark_onWarning,
  mp_color_dark_onInfo,
  mp_color_dark_primaryContainer,
  mp_color_dark_onPrimaryContainer,
  mp_color_dark_successContainer,
  mp_color_dark_onSuccessContainer,
  mp_color_dark_warningContainer,
  mp_color_dark_onWarningContainer,
  mp_color_dark_errorContainer,
  mp_color_dark_onErrorContainer,
  mp_color_dark_surfaceBright,
  mp_color_dark_outline,
  mp_color_dark_outlineVariant,
  mp_color_dark_border,
  mp_color_dark_textPrimary,
  mp_color_dark_blue50,
  mp_color_dark_blue100,
  mp_color_dark_blue200,
  mp_color_dark_blue700,
  mp_color_dark_blue900,
  mp_color_dark_neutral100,
  mp_color_dark_neutral200,
  mp_color_dark_flowLogic_primary,
  mp_color_dark_flowLogic_onPrimary,
  mp_color_dark_flowLogic_container,
  mp_typography_fontFamily_base,
  mp_component_button_typography_fontSize,
  mp_component_button_typography_fontWeight,
  mp_component_button_typography_letterSpacing,
  mp_component_button_radius_default,
} from '@/design-tokens/generated/tokens'

export const maropostLight = {
  dark: false,
  colors: {
    // Accessibility note:
    // Prefer blue-700 (#0A7AB5) or darker for text on light surfaces.
    // blue-500 / blue-600 are accent tones and may fail AA for body-size text.
    background: mp_color_light_background,
    surface: mp_color_light_surface,
    'surface-variant': mp_color_light_surfaceVariant,
    'surface-tint': mp_color_light_surfaceTint,
    'on-surface-variant': mp_color_light_onSurfaceVariant,
    primary: mp_color_light_primary,
    'primary-darken-1': mp_color_light_primaryDarken,
    secondary: mp_color_light_secondary,
    'secondary-darken-1': mp_color_light_secondaryDarken,
    success: mp_color_light_success,
    'success-darken-1': mp_color_light_successDarken,
    warning: mp_color_light_warning,
    'warning-darken-1': mp_color_light_warningDarken,
    error: mp_color_light_error,
    'error-darken-1': mp_color_light_errorDarken,
    info: mp_color_light_info,
    border: mp_color_light_border,
    'on-primary': mp_color_light_onPrimary,
    'on-secondary': mp_color_light_onSecondary,
    'on-success': mp_color_light_onSuccess,
    'on-error': mp_color_light_onError,
    'on-warning': mp_color_light_onWarning,
    'on-surface': mp_color_light_textPrimary,
    'on-background': mp_color_light_textPrimary,
    'blue-50': mp_color_blue_50,
    'blue-100': mp_color_blue_100,
    'blue-200': mp_color_blue_200,
    'blue-700': mp_color_blue_700,
    'blue-900': mp_color_blue_900,
    'primary-container': mp_color_light_primaryContainer,
    'on-primary-container': mp_color_light_onPrimaryContainer,
    'success-container': mp_color_light_successContainer,
    'on-success-container': mp_color_light_onSuccessContainer,
    'warning-container': mp_color_light_warningContainer,
    'on-warning-container': mp_color_light_onWarningContainer,
    'error-container': mp_color_light_errorContainer,
    'on-error-container': mp_color_light_onErrorContainer,
    'surface-bright': mp_color_light_surfaceBright,
    outline: mp_color_light_outline,
    'outline-variant': mp_color_light_outlineVariant,
    'neutral-100': mp_color_neutral_100,
    'neutral-200': mp_color_neutral_200,
    'flow-logic': mp_color_light_flowLogic_primary,
    'on-flow-logic': mp_color_light_flowLogic_onPrimary,
    'flow-logic-container': mp_color_light_flowLogic_container,
  },
}

export const maropostDark = {
  dark: true,
  colors: {
    background: mp_color_dark_background,
    surface: mp_color_dark_surface,
    'surface-variant': mp_color_dark_surfaceVariant,
    'surface-tint': mp_color_dark_surfaceTint,
    'on-surface-variant': mp_color_dark_onSurfaceVariant,
    primary: mp_color_dark_primary,
    'primary-darken-1': mp_color_dark_primaryDarken,
    secondary: mp_color_dark_secondary,
    'secondary-darken-1': mp_color_dark_secondaryDarken,
    success: mp_color_dark_success,
    'success-darken-1': mp_color_dark_successDarken,
    warning: mp_color_dark_warning,
    'warning-darken-1': mp_color_dark_warningDarken,
    error: mp_color_dark_error,
    'error-darken-1': mp_color_dark_errorDarken,
    info: mp_color_dark_info,
    border: mp_color_dark_border,
    'on-primary': mp_color_dark_onPrimary,
    'on-secondary': mp_color_dark_onSecondary,
    'on-success': mp_color_dark_onSuccess,
    'on-error': mp_color_dark_onError,
    'on-warning': mp_color_dark_onWarning,
    'on-info': mp_color_dark_onInfo,
    'on-surface': mp_color_dark_textPrimary,
    'on-background': mp_color_dark_textPrimary,
    'blue-50': mp_color_dark_blue50,
    'blue-100': mp_color_dark_blue100,
    'blue-200': mp_color_dark_blue200,
    'blue-700': mp_color_dark_blue700,
    'blue-900': mp_color_dark_blue900,
    'primary-container': mp_color_dark_primaryContainer,
    'on-primary-container': mp_color_dark_onPrimaryContainer,
    'success-container': mp_color_dark_successContainer,
    'on-success-container': mp_color_dark_onSuccessContainer,
    'warning-container': mp_color_dark_warningContainer,
    'on-warning-container': mp_color_dark_onWarningContainer,
    'error-container': mp_color_dark_errorContainer,
    'on-error-container': mp_color_dark_onErrorContainer,
    'surface-bright': mp_color_dark_surfaceBright,
    outline: mp_color_dark_outline,
    'outline-variant': mp_color_dark_outlineVariant,
    'neutral-100': mp_color_dark_neutral100,
    'neutral-200': mp_color_dark_neutral200,
    'flow-logic': mp_color_dark_flowLogic_primary,
    'on-flow-logic': mp_color_dark_flowLogic_onPrimary,
    'flow-logic-container': mp_color_dark_flowLogic_container,
  },
}

export const maropostDefaults = {
  VBtn: {
    variant: 'flat',
    style: `
      letter-spacing: ${mp_component_button_typography_letterSpacing};
      font-weight: ${mp_component_button_typography_fontWeight};
      text-transform: none;
      font-family: ${mp_typography_fontFamily_base};
      font-size: ${mp_component_button_typography_fontSize};
      border-radius: ${mp_component_button_radius_default};
      min-height: 40px;
      padding-inline: 14px;
    `,
  },
  VCard: {
    variant: 'flat',
    rounded: 'lg',
  },
  // Field chrome (borders, radius, states) is owned by settings-form.scss —
  // keep these defaults behavioral only.
  VTextField: {
    variant: 'outlined',
    density: 'comfortable',
    hideDetails: 'auto',
    color: 'primary',
  },
  VSelect: {
    variant: 'outlined',
    density: 'comfortable',
    hideDetails: 'auto',
    color: 'primary',
  },
  VAutocomplete: {
    variant: 'outlined',
    density: 'comfortable',
    hideDetails: 'auto',
    color: 'primary',
  },
  VCombobox: {
    variant: 'outlined',
    density: 'comfortable',
    hideDetails: 'auto',
    color: 'primary',
  },
  VTextarea: {
    variant: 'outlined',
    density: 'comfortable',
    hideDetails: 'auto',
    color: 'primary',
  },
  VAlert: {
    variant: 'tonal',
    rounded: 'md',
  },
  VChip: {
    rounded: 'pill',
    size: 'small',
  },
  VDataTable: {
    fixedHeader: true,
    hover: true,
    density: 'comfortable',
    itemsPerPage: 15,
  },
  VNavigationDrawer: {
    elevation: 0,
  },
  VAppBar: {
    elevation: 0,
  },
  VDivider: {
    opacity: 0.72,
  },
  VList: {
    elevation: 0,
    border: true,
    rounded: 'lg',
  },
}
